name: CI Build and Deploy

on:
  push:
    branches:
      - "stage"

jobs:
  build:

    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Webservice
        uses: actions/upload-artifact@v3
        with:
          name: paladins-webservice
          path: D:\a\paladins-cheat-backend\paladins-cheat-backend\paladins-webservice\target\paladins-webservice.jar

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Webservice
        uses: actions/download-artifact@v3
        with:
          name: paladins-webservice

      - name: Deploy Webservice
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'paladins'
          password: ${{ secrets.SFTP_PASSWORD }}
          server: '202.61.202.50'
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: '*.jar'
          remote_path: '/home/paladins/webservice'
          sftp-only: true
